<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Ardalis.Specification" Version="9.3.1" />
    <PackageVersion Include="Ardalis.Specification.EntityFrameworkCore" Version="9.3.1" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="8.0.20" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL.Design" Version="1.1.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11" />
  </ItemGroup>
</Project>